version: "3.8"

services:
  web:
    container_name: meisterumzuege24-prod
    build: .
    image: meisterumzuege24:latest
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - /etc/ssl/cloudflare:/etc/ssl/cloudflare:ro
    networks:
      - internal

networks:
  internal: {} 