version: '3.8'

services:
  meisterumzuege24:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meisterumzuege24-web
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: mount logs for debugging
      - ./logs:/var/log/nginx
    networks:
      - meisterumzuege24-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy with SSL
  nginx-proxy:
    image: nginx:alpine
    container_name: meisterumzuege24-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - meisterumzuege24
    networks:
      - meisterumzuege24-network
    restart: unless-stopped
    profiles:
      - ssl

networks:
  meisterumzuege24-network:
    driver: bridge 